# The URL the site will be built for
base_url = "https://bjornelvar.dev"
theme = "zola-resume"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
title = "Bjössi"
description = "A clean resume theme"
generate_feed = true
taxonomies = [
  { name = "tags", feed = true },
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "OneHalfLight"

[extra]
# Put all your custom variables here
first_name = "Björn Elvar"
last_name = "Þorleifsson"
address = "Reykjavík / Chicago"
email = "bjornelvar@icloud.com"
favicon = "/media/memoji.png"
avatar = "/media/mois.jpg"

show_about = true
show_skills = true
show_projects = true
show_opensource = false
show_publications = false
show_experience = true
show_education = true
show_blog = false
